# Generated by Django 4.0.8 on 2023-03-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disability_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disable',
            name='picture',
            field=models.ImageField(null=True, upload_to='Disability_Management/static/images'),
        ),
    ]
