# Generated by Django 4.0.8 on 2023-03-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disability_Management', '0003_alter_disable_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disable',
            name='date',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
