# Generated by Django 4.0.8 on 2023-03-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Disability_Management', '0004_alter_disable_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='disable',
            name='birth_day',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
